<!DOCTYPE html>
<html>
<head>
	<title>:)</title>
	<style>
	body {
		display: flex;
	}

	.a {
		width: 100px;
		height: 100px;
		background-color: #263145 ;
	}

	.b {
		width: 100px;
		height: 100px;
		background-color: #d8d7e0;
	}

	.c {
		width: 100px;
		height: 100px;
		background-color: #5d4c56;
	}

	.d {
		width: 100px;
		height: 100px;
		background-color: #6a7ea4;
	}

	.e {
		width: 100px;
		height: 100px;
		background-color: #906e59;
	}

	.f {
		width: 100px;
		height: 100px;
		background-color: #9dadcc;
	}

	.g {
		width: 100px;
		height: 100px;
		background-color: #a48682;
	}

	.h {
		width: 100px;
		height: 100px;
		background-color: #bfa295;
	}

	.i {
		width: 100px;
		height: 100px;
		background-color: #447ca9;
	}

	</style>
</head>
<body>
<div class='a'></div>
<div class='b'></div>
<div class='c'></div>
<div class='d'></div>
<div class='e'></div>
<div class='f'></div>
<div class='g'></div>
<div class='h'></div>
<div class='i'></div>
</body>
</html>